# https://www.playframework.com/documentation/latest/Configuration
play.server.http.port = 9000

play.filters.enabled += "play.filters.cors.CORSFilter"

play.filters.cors {
  allowedOrigins = ["http://localhost:5173"]
  allowedHttpMethods = ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
  allowedHttpHeaders = ["Accept", "Content-Type", "Origin"]
}

slick.dbs.default.profile = "slick.jdbc.PostgresProfile$"
slick.dbs.default.db.driver = "org.postgresql.Driver"
slick.dbs.default.db.url = ${?DB_URL}
slick.dbs.default.db.user = ${?DB_USER}
slick.dbs.default.db.password = ${?DB_PASSWORD}

jwt.secret = ${?JWT_SECRET}

play.modules.enabled += "play.api.libs.ws.ahc.AhcWSModule"
play.modules.enabled += "play.api.db.HikariCPModule"
play.modules.enabled += "play.api.db.slick.SlickModule"

play.modules.enabled += "modules.ClockModule"